services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-dev-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: todo-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@todo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - todo-dev-network

volumes:
  postgres_dev_data:

networks:
  todo-dev-network:
    driver: bridge
