version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U todo_user -d todo_db']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@db:5432/todo_db?schema=public
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1h
    ports:
      - '3000:3000'
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/main.js
      "
